# Generated by Django 5.2 on 2025-04-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
