# Generated by Django 5.2 on 2025-04-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_quiz', '0002_customuser_token_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='definition_lang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='term_lang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
